# This is supposed to be the API specification
# There will be 5 end points

openapi: 3.0.0
info:
  title: Image manipulation API
  description: API that takes an image and returns a manipulated image based on user request by Chad R. Stewart
  contact:
    name: Chad R. Stewart
    url: https://wwww.twitter.com/Chad_R_Stewart
  version: 1.0.0
servers:
  - url: https://localhost:3000
paths:
  /image/resize/:
    description: Resize a png image
    post:
      description: Takes an image with a percentage scale between 1 - 99 and returns the image to that scale
      tags:
        - resize
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - percentageScale
                - base64String
              properties:
                percentageScale:
                  type: number
                  description: The scale between 1 - 99 in which the book can be resized.
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                percentageScale: 40
                base64String: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
    get:
      tags:
        - resize
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    put:
      tags:
        - resize
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    patch:
      tags:
        - resize
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    delete:
      tags:
        - resize
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
  /image/grayscale:
    description: Makes an image grayscale
    post:
      description: Takes an image returns the image in grayscale
      tags:
        - grayscale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - base64String
              properties:
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                base64String: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
    get:
      tags:
        - grayscale
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    put:
      tags:
        - grayscale
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    patch:
      tags:
        - grayscale
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    delete:
      tags:
        - grayscale
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
  /image/transformation:
    description: Transforms an image
    post:
      description: Takes an image with a transformation type and parameters on how to conduct that transformation and returns an image based on those specifications
      tags:
        - transformation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transformation-specs
                - base64String
              properties:
                transformation-specs:
                  type: object
                  description: specifications on the transformation based on the type
                base64String:
                  type: string
                  description: The image as a base64 string
              example:
                transformation-specs: { "resizeScale": 40, "rotation": 60, "x-axis-flip": "true", "y-axis-flip": "true" }
                base64String: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
      responses:
        200:
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: true
                  message: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="

        400:
          description: This is not a properly formatted base64 image
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "This is not a properly formatted base64 image"
        415:
          description: Please send an image that is .jpg, .jpeg, .jpe or .png
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "Please send an image that is .jpg, .jpeg, .jpe or .png"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the response was a success or not
                  message:
                    type: string
                    description: Content of the response
                example:
                  success: false
                  message: "There was an internal server error"
    get:
      tags:
        - transformation
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    put:
      tags:
        - transformation
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    patch:
      tags:
        - transformation
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
    delete:
      tags:
        - transformation
      responses:
        501:
          description: Not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/NotImplemented'
components:
  NotImplemented:
    type: object
    properties:
      success:
        type: boolean
        description: Whether the response was a success or not
      message:
        type: string
        description: Content of the response
    example:
      success: false
      message: "This HTTP verb is not implemented"
    
# Need to implement two more paths for two image manipulations specified from 3rd party library